/**
* The MIT License
* Copyright (c) 2016 Population Register Centre (VRK)
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTV.IdentityUserManager.Resources {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Shared__Layout {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Shared__Layout() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTV.IdentityUserManager.Resources.SharedResource", typeof(Views_Shared__Layout).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string sts_EnvironmentDEV
        {
            get
            {
                return ResourceManager.GetString("sts_EnvironmentDEV", resourceCulture);
            }
        }

        internal static string sts_EnvironmentTEST
        {
            get
            {
                return ResourceManager.GetString("sts_EnvironmentTEST", resourceCulture);
            }
        }

        internal static string sts_EnvironmentQA
        {
            get
            {
                return ResourceManager.GetString("sts_EnvironmentQA", resourceCulture);
            }
        }

        internal static string sts_EnvironmentTRN
        {
            get
            {
                return ResourceManager.GetString("sts_EnvironmentTRN", resourceCulture);
            }
        }

        internal static string sts_EnvironmentPROD
        {
            get
            {
                return ResourceManager.GetString("sts_EnvironmentPROD", resourceCulture);
            }
        }

        internal static string sts_ServiceName
        {
            get
            {
                return ResourceManager.GetString("sts_ServiceName", resourceCulture);
            }
        }

        internal static string sts_FooterServiceProviderDescription
        {
            get
            {
                return ResourceManager.GetString("sts_FooterServiceProviderDescription", resourceCulture);
            }
        }

        internal static string sts_FooterServiceProvider
        {
            get
            {
                return ResourceManager.GetString("sts_FooterServiceProvider", resourceCulture);
            }
        }

        internal static string sts_FooterServiceProviderLink
        {
            get
            {
                return ResourceManager.GetString("sts_FooterServiceProviderLink", resourceCulture);
            }
        }

        internal static string sts_FooterPrivacyPolicy
        {
            get
            {
                return ResourceManager.GetString("sts_FooterPrivacyPolicy", resourceCulture);
            }
        }

        internal static string sts_FooterPrivacyPolicyLink
        {
            get
            {
                return ResourceManager.GetString("sts_FooterPrivacyPolicyLink", resourceCulture);
            }
        }

        internal static string sts_FooterFeedback
        {
            get
            {
                return ResourceManager.GetString("sts_FooterFeedback", resourceCulture);
            }
        }

        internal static string sts_FooterFeedbackLink
        {
            get
            {
                return ResourceManager.GetString("sts_FooterFeedbackLink", resourceCulture);
            }
        }

        internal static string sts_FooterAboutService
        {
            get
            {
                return ResourceManager.GetString("sts_FooterAboutService", resourceCulture);
            }
        }

        internal static string sts_FooterAboutServiceLink
        {
            get
            {
                return ResourceManager.GetString("sts_FooterAboutServiceLink", resourceCulture);
            }
        }

        internal static string sts_FooterSourceCodeDescription
        {
            get
            {
                return ResourceManager.GetString("sts_FooterSourceCodeDescription", resourceCulture);
            }
        }

        internal static string sts_FooterSourceCode
        {
            get
            {
                return ResourceManager.GetString("sts_FooterSourceCode", resourceCulture);
            }
        }

        internal static string sts_FooterSourceCodeLink
        {
            get
            {
                return ResourceManager.GetString("sts_FooterSourceCodeLink", resourceCulture);
            }
        }

        internal static string sts_FooterPublicWeb
        {
            get
            {
                return ResourceManager.GetString("sts_FooterPublicWeb", resourceCulture);
            }
        }

        internal static string sts_FooterPublicWebLink
        {
            get
            {
                return ResourceManager.GetString("sts_FooterPublicWebLink", resourceCulture);
            }
        }
    }
}
