/**
* The MIT License
* Copyright (c) 2016 Population Register Centre (VRK)
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTV.IdentityUserManager.Resources {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Account_Index {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Account_Index() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTV.IdentityUserManager.Resources.Common", typeof(Views_Account_Index).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string sts_LoginButton {
            get {
                return ResourceManager.GetString("sts_LoginButton", resourceCulture);
            }
        }

        internal static string sts_LoginDescription {
            get {
                return ResourceManager.GetString("sts_LoginDescription", resourceCulture);
            }
        }

        internal static string sts_LoginEmail {
            get {
                return ResourceManager.GetString("sts_LoginEmail", resourceCulture);
            }
        }

        internal static string sts_LoginHeader {
            get {
                return ResourceManager.GetString("sts_LoginHeader", resourceCulture);
            }
        }

        internal static string sts_LoginPassword {
            get {
                return ResourceManager.GetString("sts_LoginPassword", resourceCulture);
            }
        }

        internal static string sts_LoginRememberMe {
            get {
                return ResourceManager.GetString("sts_LoginRememberMe", resourceCulture);
            }
        }

        internal static string sts_WelcomeMessage1 {
            get {
                return ResourceManager.GetString("sts_WelcomeMessage1", resourceCulture);
            }
        }

        internal static string sts_WelcomeMessage2 {
            get {
                return ResourceManager.GetString("sts_WelcomeMessage2", resourceCulture);
            }
        }


        internal static string sts_WelcomeMessage3_1 {
            get {
                return ResourceManager.GetString("sts_WelcomeMessage3_1", resourceCulture);
            }
        }

        internal static string sts_WelcomeMessage3_2 {
            get {
                return ResourceManager.GetString("sts_WelcomeMessage3_2", resourceCulture);
            }
        }

        internal static string sts_ReadMoreTitle {
            get {
                return ResourceManager.GetString("sts_ReadMoreTitle", resourceCulture);
            }
        }

        internal static string sts_ReadMoreLink {
            get {
                return ResourceManager.GetString("sts_ReadMoreLink", resourceCulture);
            }
        }

        internal static string sts_LoginEmailPlaceholder {
            get {
                return ResourceManager.GetString("sts_LoginEmailPlaceholder", resourceCulture);
            }
        }

        internal static string sts_LoginPasswordPlaceholder {
            get {
                return ResourceManager.GetString("sts_LoginPasswordPlaceholder", resourceCulture);
            }
        }
    }
}
