


// Generated helper templates
// Generated items
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\WebPageTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\WebPageTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\WebpageChannelUrlRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\WebpageChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\WebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\VersioningRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\UserOrganizationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\TargetGroupNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\TargetGroupRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StreetNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceTargetGroupRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceServiceClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceRequirementRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceOntologyTermRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceLifeEventRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceLawRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceLanguageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceIndustrialClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceGeneralDescriptionVersionedRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceGeneralDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\StatutoryServiceDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceVersionedRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceTargetGroupRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceServiceClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceServiceChannelDigitalAuthorizationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceServiceChannelDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceServiceChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceRequirementRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceOntologyTermRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceLocationChannelAddressRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceLocationChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceLifeEventRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceLawRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceLanguageAvailabilityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceLanguageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceKeywordRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceIndustrialClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceHourTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceHourTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceHoursAdditionalInformationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceFundingTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceFundingTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceElectronicNotificationChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceElectronicCommunicationChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceClassNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChargeTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChargeTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelVersionedRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelTargetGroupRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelServiceHoursRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelServiceClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelPhoneRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelOntologyTermRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelLanguageAvailabilityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelLanguageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelKeywordRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelEmailRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelConnectionTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelConnectionTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelAttachmentRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelAreaMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelAreaRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceBlockedAccessRightRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceAreaMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceAreaRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ServiceRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\RoleTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\RoleTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PublishingStatusTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PublishingStatusTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ProvisionTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ProvisionTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PrintableFormChannelUrlTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PrintableFormChannelUrlTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PrintableFormChannelUrlRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PrintableFormChannelReceiverRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PrintableFormChannelIdentifierRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PrintableFormChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PostOfficeBoxNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PostalCodeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PostalCodeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PhoneNumberTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PhoneNumberTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\PhoneRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationVersionedRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationServiceAdditionalInformationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationServiceRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationPhoneRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationLanguageAvailabilityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationEmailRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationDisplayNameTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationBlockedAccessRightRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationAreaMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationAreaRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationAddressRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OrganizationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OntologyTermParentRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OntologyTermNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OntologyTermExactMatchRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\OntologyTermRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\NameTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\NameTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\MunicipalityNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\MunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\LockingRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\LifeEventNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\LifeEventRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\LawWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\LawNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\LawRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\LanguageNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\LanguageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\KeywordRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\IndustrialClassNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\IndustrialClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\GeneralDescriptionLanguageAvailabilityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\GeneralDescriptionBlockedAccessRightRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\FormTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\FormTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\FormRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ExternalSourceRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ExceptionHoursStatusTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ExceptionHoursStatusTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ExactMatchRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\EmailRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ElectronicChannelUrlRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ElectronicChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\DigitalAuthorizationNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\DigitalAuthorizationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\DialCodeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\DescriptionTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\DescriptionTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\DailyOpeningTimeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\CountryNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\CountryRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\CoordinateTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\CoordinateTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\CoordinateRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\ChannelBlockedAccessRightRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\BusinessRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\BugReportRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AttachmentTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AttachmentTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AttachmentRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AreaTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AreaTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AreaNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AreaMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AreaInformationTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AreaInformationTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AreaRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AppEnvironmentDataTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AppEnvironmentDataTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AppEnvironmentDataRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AddressTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AddressTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AddressAdditionalInformationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AddressRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AccessRightTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess\Repositories\AccessRightNameRepository.cs
