//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lingsoft
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", ConfigurationName="Lingsoft.LLSOrdersPort")]
    public interface LLSOrdersPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://llso-test.lingsoft.fi/api/v2/#OrderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Lingsoft.OrderStatusResponse> OrderStatusAsync(Lingsoft.OrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://llso-test.lingsoft.fi/api/v2/#OrderStatuses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Lingsoft.OrderStatusesResponse> OrderStatusesAsync(Lingsoft.OrderStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://llso-test.lingsoft.fi/api/v2/#CancelOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Lingsoft.CancelOrderResponse> CancelOrderAsync(Lingsoft.CancelOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://llso-test.lingsoft.fi/api/v2/#QueryWorkId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Lingsoft.QueryWorkIdResponse> QueryWorkIdAsync(Lingsoft.QueryWorkIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://llso-test.lingsoft.fi/api/v2/#UpdateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Lingsoft.UpdateOrderResponse> UpdateOrderAsync(Lingsoft.UpdateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://llso-test.lingsoft.fi/api/v2/#NewOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Lingsoft.NewOrderResponse> NewOrderAsync(Lingsoft.NewOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/")]
    public partial class Status
    {
        
        private string orderIDField;
        
        private string stateField;
        
        private string contactField;
        
        private string phoneNumberField;
        
        private string validationResultField;
        
        private string fileUrlField;
        
        private string quoteField;
        
        private string deadlineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string orderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string validationResult
        {
            get
            {
                return this.validationResultField;
            }
            set
            {
                this.validationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string fileUrl
        {
            get
            {
                return this.fileUrlField;
            }
            set
            {
                this.fileUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quote
        {
            get
            {
                return this.quoteField;
            }
            set
            {
                this.quoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string deadline
        {
            get
            {
                return this.deadlineField;
            }
            set
            {
                this.deadlineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/")]
    public partial class trgLang
    {
        
        private string trgLang1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trgLang", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string trgLang1
        {
            get
            {
                return this.trgLang1Field;
            }
            set
            {
                this.trgLang1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/")]
    public partial class Order
    {
        
        private string orderIDField;
        
        private string endCustomerField;
        
        private string ordererAccountField;
        
        private string emailField;
        
        private string pmField;
        
        private string deadlineField;
        
        private string clientRefField;
        
        private string clientInfoField;
        
        private string vendorInstructionsField;
        
        private System.Nullable<int> workTypeField;
        
        private System.Nullable<int> docTypeField;
        
        private string orderTypeField;
        
        private string filesUrlField;
        
        private string downloadedUrlField;
        
        private string analysisField;
        
        private string projectReadyCallbackUrlField;
        
        private string nameField;
        
        private string srcLangField;
        
        private trgLang[] trgLangListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string orderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string endCustomer
        {
            get
            {
                return this.endCustomerField;
            }
            set
            {
                this.endCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ordererAccount
        {
            get
            {
                return this.ordererAccountField;
            }
            set
            {
                this.ordererAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string pm
        {
            get
            {
                return this.pmField;
            }
            set
            {
                this.pmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string deadline
        {
            get
            {
                return this.deadlineField;
            }
            set
            {
                this.deadlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string clientRef
        {
            get
            {
                return this.clientRefField;
            }
            set
            {
                this.clientRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string clientInfo
        {
            get
            {
                return this.clientInfoField;
            }
            set
            {
                this.clientInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string vendorInstructions
        {
            get
            {
                return this.vendorInstructionsField;
            }
            set
            {
                this.vendorInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> workType
        {
            get
            {
                return this.workTypeField;
            }
            set
            {
                this.workTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> docType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string orderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string filesUrl
        {
            get
            {
                return this.filesUrlField;
            }
            set
            {
                this.filesUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string downloadedUrl
        {
            get
            {
                return this.downloadedUrlField;
            }
            set
            {
                this.downloadedUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string analysis
        {
            get
            {
                return this.analysisField;
            }
            set
            {
                this.analysisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string projectReadyCallbackUrl
        {
            get
            {
                return this.projectReadyCallbackUrlField;
            }
            set
            {
                this.projectReadyCallbackUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string srcLang
        {
            get
            {
                return this.srcLangField;
            }
            set
            {
                this.srcLangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public trgLang[] trgLangList
        {
            get
            {
                return this.trgLangListField;
            }
            set
            {
                this.trgLangListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/")]
    public partial class StatusArray
    {
        
        private Status[] statusesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Status[] statuses
        {
            get
            {
                return this.statusesField;
            }
            set
            {
                this.statusesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderStatus", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class OrderStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llsoWorkID;
        
        public OrderStatusRequest()
        {
        }
        
        public OrderStatusRequest(string llsoWorkID)
        {
            this.llsoWorkID = llsoWorkID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderStatusResponse", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class OrderStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Lingsoft.Status OrderStatusResult;
        
        public OrderStatusResponse()
        {
        }
        
        public OrderStatusResponse(Lingsoft.Status OrderStatusResult)
        {
            this.OrderStatusResult = OrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderStatuses", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class OrderStatusesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llsoWorkIDs;
        
        public OrderStatusesRequest()
        {
        }
        
        public OrderStatusesRequest(string llsoWorkIDs)
        {
            this.llsoWorkIDs = llsoWorkIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderStatusesResponse", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class OrderStatusesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Lingsoft.StatusArray OrderStatusesResult;
        
        public OrderStatusesResponse()
        {
        }
        
        public OrderStatusesResponse(Lingsoft.StatusArray OrderStatusesResult)
        {
            this.OrderStatusesResult = OrderStatusesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelOrder", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class CancelOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llsoWorkID;
        
        public CancelOrderRequest()
        {
        }
        
        public CancelOrderRequest(string llsoWorkID)
        {
            this.llsoWorkID = llsoWorkID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelOrderResponse", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class CancelOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CancelOrderResult;
        
        public CancelOrderResponse()
        {
        }
        
        public CancelOrderResponse(bool CancelOrderResult)
        {
            this.CancelOrderResult = CancelOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryWorkId", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class QueryWorkIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderID;
        
        public QueryWorkIdRequest()
        {
        }
        
        public QueryWorkIdRequest(string orderID)
        {
            this.orderID = orderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryWorkIdResponse", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class QueryWorkIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryWorkIdResult;
        
        public QueryWorkIdResponse()
        {
        }
        
        public QueryWorkIdResponse(string QueryWorkIdResult)
        {
            this.QueryWorkIdResult = QueryWorkIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateOrder", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class UpdateOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llsoWorkID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Lingsoft.Order order;
        
        public UpdateOrderRequest()
        {
        }
        
        public UpdateOrderRequest(string llsoWorkID, Lingsoft.Order order)
        {
            this.llsoWorkID = llsoWorkID;
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateOrderResponse", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class UpdateOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UpdateOrderResult;
        
        public UpdateOrderResponse()
        {
        }
        
        public UpdateOrderResponse(string UpdateOrderResult)
        {
            this.UpdateOrderResult = UpdateOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewOrder", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class NewOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Lingsoft.Order order;
        
        public NewOrderRequest()
        {
        }
        
        public NewOrderRequest(Lingsoft.Order order)
        {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewOrderResponse", WrapperNamespace="https://llso-test.lingsoft.fi/api/v2/", IsWrapped=true)]
    public partial class NewOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://llso-test.lingsoft.fi/api/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewOrderResult;
        
        public NewOrderResponse()
        {
        }
        
        public NewOrderResponse(string NewOrderResult)
        {
            this.NewOrderResult = NewOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface LLSOrdersPortChannel : Lingsoft.LLSOrdersPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class LLSOrdersPortClient : System.ServiceModel.ClientBase<Lingsoft.LLSOrdersPort>, Lingsoft.LLSOrdersPort
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LLSOrdersPortClient() : 
                base(LLSOrdersPortClient.GetDefaultBinding(), LLSOrdersPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LLSOrdersPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LLSOrdersPortClient(EndpointConfiguration endpointConfiguration) : 
                base(LLSOrdersPortClient.GetBindingForEndpoint(endpointConfiguration), LLSOrdersPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LLSOrdersPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LLSOrdersPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LLSOrdersPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LLSOrdersPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LLSOrdersPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lingsoft.OrderStatusResponse> Lingsoft.LLSOrdersPort.OrderStatusAsync(Lingsoft.OrderStatusRequest request)
        {
            return base.Channel.OrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lingsoft.OrderStatusResponse> OrderStatusAsync(string llsoWorkID)
        {
            Lingsoft.OrderStatusRequest inValue = new Lingsoft.OrderStatusRequest();
            inValue.llsoWorkID = llsoWorkID;
            return ((Lingsoft.LLSOrdersPort)(this)).OrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lingsoft.OrderStatusesResponse> Lingsoft.LLSOrdersPort.OrderStatusesAsync(Lingsoft.OrderStatusesRequest request)
        {
            return base.Channel.OrderStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lingsoft.OrderStatusesResponse> OrderStatusesAsync(string llsoWorkIDs)
        {
            Lingsoft.OrderStatusesRequest inValue = new Lingsoft.OrderStatusesRequest();
            inValue.llsoWorkIDs = llsoWorkIDs;
            return ((Lingsoft.LLSOrdersPort)(this)).OrderStatusesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lingsoft.CancelOrderResponse> Lingsoft.LLSOrdersPort.CancelOrderAsync(Lingsoft.CancelOrderRequest request)
        {
            return base.Channel.CancelOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lingsoft.CancelOrderResponse> CancelOrderAsync(string llsoWorkID)
        {
            Lingsoft.CancelOrderRequest inValue = new Lingsoft.CancelOrderRequest();
            inValue.llsoWorkID = llsoWorkID;
            return ((Lingsoft.LLSOrdersPort)(this)).CancelOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lingsoft.QueryWorkIdResponse> Lingsoft.LLSOrdersPort.QueryWorkIdAsync(Lingsoft.QueryWorkIdRequest request)
        {
            return base.Channel.QueryWorkIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lingsoft.QueryWorkIdResponse> QueryWorkIdAsync(string orderID)
        {
            Lingsoft.QueryWorkIdRequest inValue = new Lingsoft.QueryWorkIdRequest();
            inValue.orderID = orderID;
            return ((Lingsoft.LLSOrdersPort)(this)).QueryWorkIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lingsoft.UpdateOrderResponse> Lingsoft.LLSOrdersPort.UpdateOrderAsync(Lingsoft.UpdateOrderRequest request)
        {
            return base.Channel.UpdateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lingsoft.UpdateOrderResponse> UpdateOrderAsync(string llsoWorkID, Lingsoft.Order order)
        {
            Lingsoft.UpdateOrderRequest inValue = new Lingsoft.UpdateOrderRequest();
            inValue.llsoWorkID = llsoWorkID;
            inValue.order = order;
            return ((Lingsoft.LLSOrdersPort)(this)).UpdateOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lingsoft.NewOrderResponse> Lingsoft.LLSOrdersPort.NewOrderAsync(Lingsoft.NewOrderRequest request)
        {
            return base.Channel.NewOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lingsoft.NewOrderResponse> NewOrderAsync(Lingsoft.Order order)
        {
            Lingsoft.NewOrderRequest inValue = new Lingsoft.NewOrderRequest();
            inValue.order = order;
            return ((Lingsoft.LLSOrdersPort)(this)).NewOrderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LLSOrdersPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LLSOrdersPort))
            {
                return new System.ServiceModel.EndpointAddress("https://llso-test.lingsoft.fi/api/v2/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LLSOrdersPortClient.GetBindingForEndpoint(EndpointConfiguration.LLSOrdersPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LLSOrdersPortClient.GetEndpointAddress(EndpointConfiguration.LLSOrdersPort);
        }
        
        public enum EndpointConfiguration
        {
            
            LLSOrdersPort,
        }
    }
}
