namespace PTV.ExternalData.Pharmacy

open System.Collections.Generic
open FSharp.Data

// This file contains type definitions used in the rest of the AWS lambda function.
// If you want to know how the F# code works, start in the Function.fs file.

/// A static type for the pharmacies XML dynamically generated by FSharp.Data.
type PharmaciesXml = XmlProvider<"./Resources/Pharmacies.xml">

type ServiceLocationJson = JsonProvider<"./Resources/ServiceLocationV11Put.json", RootName="serviceLocation">

type EChannelJson = JsonProvider<"./Resources/EChannelV11Put.json", RootName="eChannel">

type ConnectionJson = JsonProvider<"./Resources/ConnectionV11Post.json", RootName="connection">

type LoginRequestJson = JsonProvider<"./Resources/LoginRequest.json", RootName="request">

type LoginResponseJson = JsonProvider<"./Resources/LoginResponse.json", RootName="response">

type OrganizationServiceChannelJson = JsonProvider<"./Resources/OrganizationServiceChannel.json", RootName="page">

type ArchiveJson = JsonProvider<"./Resources/ArchiveJson.json", RootName="request">

type EnumCache = {
  LanguageCodes: Dictionary<string, string>
  PostOfficeMunicipalities: Dictionary<string, List<string>>;
}

type Secret = {
    DownloadUrl: string
    GetChannelUrl: string
    AuthenticationUrl: string
    PutLocationUrl: string
    PostLocationUrl: string
    PutEChannelUrl: string
    PostEChannelUrl: string
    PostConnectionUrl: string
    ApiUserName: string
    ApiPassword: string
    OrganizationId: string
    ServiceId: string
    UsePaha: bool
  }

type Weekday =
  | Monday = 1
  | Tuesday = 2
  | Wednesday = 3
  | Thursday = 4
  | Friday = 5
  | Saturday = 6
  | Sunday = 7
  
type OpeningTime =
  {
    DayFrom: Weekday option;
    TimeFrom: string option;
    DayTo: Weekday option;
    TimeTo: string option;
  }
  
type LengthDefinitions =
  {
    Name: int
    Summary: int
    Description: int
    AdditionalInfo: int
    StreetName: int
    StreetAdditionalInfo: int
    WebPage: int
    ChargeInfoMin: int
  }
  