CREATE OR REPLACE
FUNCTION SPLIT_LAST_OPERATION_FIELD(int, int)
RETURNS void
LANGUAGE plpgsql AS
$$
DECLARE
  tableNames CURSOR FOR
    SELECT table_name as tableName 
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE COLUMN_NAME = 'LastOperationId'   
    AND "table_schema" = 'public'
    ORDER BY "table_name"
    LIMIT $1 
    OFFSET $2; 
   
  columnName text;
  sqlCommand text := (
    'ALTER TABLE public.%I ADD COLUMN "LastOperationIdentifier" uuid NULL;
     ALTER TABLE public.%I ADD COLUMN "LastOperationTimeStamp" timestamp without time zone NULL; 
     ALTER TABLE public.%I ADD COLUMN "LastOperationType" text NULL; 
     UPDATE public.%I SET
    "LastOperationTimeStamp"= CASE WHEN (substr("LastOperationId",1,28) = '''') IS FALSE THEN (substr("LastOperationId",1,28)::timestamp without time zone) ELSE null END, 
    "LastOperationIdentifier"= CASE WHEN (substr("LastOperationId",30,36) = '''') IS FALSE THEN (substr("LastOperationId",30,36)::uuid) ELSE null END;'
  );    
    
BEGIN   
  FOR tableName IN tableNames LOOP
    EXECUTE format(
        sqlCommand
        ,
        tableName.tableName,
        tableName.tableName,
        tableName.tableName,
        tableName.tableName
      );  
    
  END LOOP;
END;
$$;


BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,0);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,2);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,4);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,6);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,8);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,10);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,12);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,14);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,16);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,18);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,20);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,22);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,24);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,26);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,28);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,30);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,32);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,34);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,36);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,38);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,40);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,42);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,44);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,46);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,48);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,50);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,52);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,54);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,56);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,58);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,60);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,62);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,64);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,66);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,68);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,70);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,72);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,74);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,76);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,78);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,80);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,82);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,84);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,86);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,88);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,90);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,92);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,94);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,96);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,98);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,100);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,102);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,104);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,106);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,108);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,110);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,112);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,114);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,116);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,118);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,120);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,122);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,124);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,126);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,128);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,130);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,132);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,134);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,136);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,138);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,140);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,142);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,144);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,146);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,148);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,150);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,152);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,154);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,156);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,158);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,160);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,162);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,164);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,166);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,168);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,170);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,172);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,174);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,176);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,178);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,180);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,182);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,184);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,186);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,188);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,190);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,192);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,194);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,196);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,198);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,200);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,202);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,204);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,206);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,208);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,210);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,212);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,214);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,216);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,218);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,220);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,222);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,224);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,226);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,228);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,230);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,232);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,234);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,236);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,238);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,240);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,242);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,244);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,246);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,248);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(2,250);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM SPLIT_LAST_OPERATION_FIELD(250,252);EXCEPTION WHEN duplicate_column THEN END;$$;COMMIT;

DROP FUNCTION IF EXISTS SPLIT_LAST_OPERATION_FIELD(int, int);

BEGIN; --Begin of migration transaction, EF migrations -automatically commit  