CREATE OR REPLACE
FUNCTION FILL_ALL_NULL_LAST_OPERATION_FIELDS(int, int)
RETURNS void
LANGUAGE plpgsql AS
$$
DECLARE
  tableNames CURSOR FOR
    SELECT table_name as tableName 
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE COLUMN_NAME = 'LastOperationIdentifier'     
    AND "table_schema" = 'public'
    ORDER BY "table_name"
    LIMIT $1 
    OFFSET $2;
   
  columnName text;
  sqlCommand text := (
    'UPDATE public.%I SET "LastOperationTimeStamp"= ''0001-01-01 00:00:00'' WHERE "LastOperationTimeStamp" IS NULL;
     UPDATE public.%I SET "LastOperationIdentifier"= ''00000000-0000-0000-0000-000000000000'' WHERE "LastOperationIdentifier" IS NULL;'  
  );
    
BEGIN   
  FOR tableName IN tableNames LOOP
    EXECUTE format(
        sqlCommand
        ,
        tableName.tableName,
        tableName.tableName
      );  
    
  END LOOP;
END;
$$;


BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,0);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,5);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,10);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,15);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,20);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,25);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,30);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,35);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,40);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,45);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,50);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,55);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,60);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,65);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,70);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,75);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,80);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,85);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,90);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,95);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,100);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,105);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,110);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,115);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,120);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,125);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,130);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,135);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,140);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,145);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,150);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,155);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,160);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,165);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,170);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,175);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,180);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,185);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,190);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,195);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,200);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,205);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,210);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,215);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,220);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,225);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,230);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,235);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,240);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,245);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,250);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(5,255);END;$$;COMMIT;
BEGIN; DO $$ BEGIN PERFORM FILL_ALL_NULL_LAST_OPERATION_FIELDS(250,260);END;$$;COMMIT;

DROP FUNCTION IF EXISTS FILL_ALL_NULL_LAST_OPERATION_FIELDS(int, int);

BEGIN; --Begin of migration transaction, EF migrations -automatically commit 