


// Generated helper templates
// Generated items
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IWebPageTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IWebPageTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IWebpageChannelUrlRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IWebpageChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IVersioningRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IUserOrganizationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ITargetGroupNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ITargetGroupRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStreetNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceTargetGroupRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceServiceClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceRequirementRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceOntologyTermRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceLifeEventRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceLawRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceLanguageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceIndustrialClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceGeneralDescriptionVersionedRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceGeneralDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceVersionedRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceTargetGroupRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelDigitalAuthorizationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceRequirementRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceOntologyTermRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceLocationChannelAddressRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceLocationChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceLifeEventRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceLawRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceLanguageAvailabilityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceLanguageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceKeywordRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceIndustrialClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceHourTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceHourTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceHoursAdditionalInformationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceFundingTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceFundingTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceElectronicNotificationChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceElectronicCommunicationChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceClassNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChargeTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChargeTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelVersionedRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelTargetGroupRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelServiceHoursRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelServiceClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelPhoneRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelOntologyTermRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelLanguageAvailabilityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelLanguageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelKeywordRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelEmailRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelConnectionTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelConnectionTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelAttachmentRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelAreaMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelAreaRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceBlockedAccessRightRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceAreaMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceAreaRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IServiceRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IRoleTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IRoleTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPublishingStatusTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPublishingStatusTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IProvisionTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IProvisionTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelUrlTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelUrlTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelUrlRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelReceiverRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelIdentifierRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPostOfficeBoxNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPostalCodeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPostalCodeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPhoneNumberTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPhoneNumberTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IPhoneRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationVersionedRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationServiceAdditionalInformationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationServiceRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationPhoneRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationLanguageAvailabilityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationEmailRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationDisplayNameTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationDescriptionRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationBlockedAccessRightRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationAreaMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationAreaRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationAddressRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermParentRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermExactMatchRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\INameTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\INameTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IMunicipalityNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ILockingRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ILifeEventNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ILifeEventRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ILawWebPageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ILawNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ILawRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ILanguageNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ILanguageRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IKeywordRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IIndustrialClassNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IIndustrialClassRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionLanguageAvailabilityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionBlockedAccessRightRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IFormTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IFormTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IFormRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IExternalSourceRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IExceptionHoursStatusTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IExceptionHoursStatusTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IExactMatchRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IEmailRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IElectronicChannelUrlRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IElectronicChannelRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IDigitalAuthorizationNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IDigitalAuthorizationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IDialCodeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IDescriptionTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IDescriptionTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IDailyOpeningTimeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ICountryNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ICountryRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ICoordinateTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ICoordinateTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\ICoordinateRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IChannelBlockedAccessRightRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IBusinessRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IBugReportRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAttachmentTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAttachmentTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAttachmentRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAreaTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAreaTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAreaNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAreaMunicipalityRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAreaInformationTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAreaInformationTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAreaRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAppEnvironmentDataTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAppEnvironmentDataTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAppEnvironmentDataRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAddressTypeNameRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAddressTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAddressAdditionalInformationRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAddressRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAccessRightTypeRepository.cs
// PTV_DEV\src\PTV.Database.DataAccess.Interfaces\Repositories\IAccessRightNameRepository.cs
