


// Generated helper templates
// Generated items
// PTV.Database.DataAccess.Interfaces\Repositories\IWebPageTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IWebPageTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IWebpageChannelUrlRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IWebpageChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IWebPageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IWcagLevelTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IWcagLevelTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IVersioningRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IUserOrganizationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IUserAccessRightsGroupNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IUserAccessRightsGroupRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITranslationStateTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITranslationStateTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITranslationOrderStateRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITranslationOrderRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITranslationCompanyRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITrackingTranslationOrderRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITrackingServiceServiceChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITrackingServiceCollectionServiceRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITrackingOrganizationChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITrackingGeneralDescriptionVersionedRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITrackingGeneralDescriptionServiceChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITrackingEntityVersionedRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITasksFilterRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITasksConfigurationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITargetGroupNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ITargetGroupRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStreetNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceTargetGroupRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceServiceClassRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceRequirementRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceOntologyTermRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceLifeEventRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceLawRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceLanguageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceIndustrialClassRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceGeneralDescriptionVersionedRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceGeneralDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IStatutoryServiceDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceWebPageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceVersionedRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceTranslationOrderRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceTargetGroupRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceClassRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelWebPageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelServiceHoursRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelPhoneRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelExtraTypeDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelExtraTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelEmailRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelDigitalAuthorizationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelAddressRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceServiceChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceRequirementRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceProducerOrganizationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceProducerAdditionalInformationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceProducerRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceOntologyTermRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceLifeEventRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceLawRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceLanguageAvailabilityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceLanguageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceKeywordRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceIndustrialClassRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceHourTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceHourTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceHoursAdditionalInformationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceHoursRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceFundingTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceFundingTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceElectronicNotificationChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceElectronicCommunicationChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceCollectionVersionedRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceCollectionServiceRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceCollectionNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceCollectionLanguageAvailabilityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceCollectionDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceCollectionBlockedAccessRightRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceCollectionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceClassNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceClassDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceClassRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChargeTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChargeTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelWebPageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelVersionedRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelTranslationOrderRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelTargetGroupRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelSocialHealthCenterRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelServiceHoursRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelServiceClassRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelPhoneRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelOntologyTermRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelLanguageAvailabilityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelLanguageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelKeywordRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelEmailRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelDisplayNameTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelConnectionTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelConnectionTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelAttachmentRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelAreaMunicipalityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelAreaRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelAddressRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceBlockedAccessRightRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceAreaMunicipalityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceAreaRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IServiceRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ISahaOrganizationInformationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IRestrictionFilterRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IRestrictedTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPublishingStatusTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPublishingStatusTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IProvisionTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IProvisionTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelUrlTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelUrlTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelUrlRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelIdentifierRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPrintableFormChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPostOfficeBoxNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPostalCodeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPostalCodeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPhoneNumberTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPhoneNumberTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPhoneExtraTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IPhoneRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationWebPageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationVersionedRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationServiceRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationPhoneRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationLanguageAvailabilityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationFilterRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationEmailRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationEInvoicingAdditionalInformationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationEInvoicingRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationDisplayNameTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationBlockedAccessRightRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationAreaMunicipalityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationAreaRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationAddressRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOrganizationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermParentRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermExactMatchRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IOntologyTermRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\INameTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\INameTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IMunicipalityNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IMunicipalityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ILockingRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ILifeEventNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ILifeEventRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ILawWebPageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ILawNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ILawRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ILanguageNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ILanguageRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IKeywordRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IIndustrialClassNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IIndustrialClassRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionTranslationOrderRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionServiceChannelExtraTypeDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionServiceChannelExtraTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionServiceChannelDigitalAuthorizationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionServiceChannelDescriptionRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionServiceChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionLanguageAvailabilityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IGeneralDescriptionBlockedAccessRightRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IFormTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IFormTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IFormStateRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IFormRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IExtraTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IExtraTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IExtraSubTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IExtraSubTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IExternalSourceRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IExceptionHoursStatusTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IExceptionHoursStatusTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IExactMatchRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IEmailRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IElectronicChannelUrlRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IElectronicChannelRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IDigitalAuthorizationNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IDigitalAuthorizationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IDialCodeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IDescriptionTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IDescriptionTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IDailyOpeningTimeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ICountryNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ICountryRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ICoordinateTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ICoordinateTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ICoordinateRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IChannelBlockedAccessRightRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\ICFGRequestFilterRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IBusinessRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IBugReportRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAuthorizationEntryPointRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAttachmentTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAttachmentTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAttachmentRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAreaTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAreaTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAreaNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAreaMunicipalityRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAreaInformationTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAreaInformationTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAreaRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAppEnvironmentDataTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAppEnvironmentDataTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAppEnvironmentDataRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressStreetRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressReceiverRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressPostOfficeBoxRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressOtherRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressForeignTextNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressForeignRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressExtraTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressCharacterNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressCharacterRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressAdditionalInformationRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAddressRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessRightTypeRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessRightsOperationsUIRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessRightNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityRegisterSentenceValueRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityRegisterSentenceRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityRegisterGroupValueRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityRegisterGroupRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityRegisterEntranceNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityRegisterEntranceRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityRegisterRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityClassificationLevelTypeNameRepository.cs
// PTV.Database.DataAccess.Interfaces\Repositories\IAccessibilityClassificationLevelTypeRepository.cs
